### PR TITLE
Provide XJC binding examples

### LINKED ISSUE #7: No xjc jaxb bindings present
I could not find an external JAXB binding to instruct the xjc code generator to use java.time instead of XMLGregorianCalendar type.

This would be a great help to have an example JAXB binding file.

Thanks,
Ken

### PR DESCRIPTION
**Pull request by mwkroening**
Resolves #7

### CODE REVIEW

**Comment by mwkroening** [comment]
@OrangeDog, @alexpercont, @gavenkoa, please review!

I used https://github.com/threeten-jaxb/threeten-jaxb/issues/7#issuecomment-470308929 and [gdpotter/jaxb-java-time](http://gdpotter.com/2017/09/21/jaxb-java-time/) as a basis.

**Comment by gavenkoa** [comment]
What is the reason to put XML inside {@code }. It is already in PRE tag...

It is probably good practice to quote open tag symbol (`<`) as `&gt;` I don't know javadoc grammar though.

**Comment by mwkroening** [comment]
I based the formatting on [HttpClient.java](https://github.com/openjdk/jdk/blob/850c34324714c3a8b18acd313d788e51f222a926/src/java.net.http/share/classes/java/net/http/HttpClient.java#L85), which was released with Java 11 so it's relatively new.

The resulting HTML looks like this:
Screenshot_2019-03-26 io github threetenjaxb core (threeten-jaxb-core 1 3-SNAPSHOT API)

**Comment by gavenkoa** [comment]
Thanks for reference. It is actually very confusing that {@code} is multiline and actual Java code example will definitely use curly braces as part of if/for/while, so it is need to worry/know about escape syntax ))

**Comment by mwkroening** [comment]
Without `<pre/>` it's not multi line though. And `{@code }` is necessary to make it ignore any inner XML nodes.

Do you approve my changes then or is there anything wrong content- or formatting-wise?

**Pull request merged**
